name: Update Readme
on:
  workflow_dispatch: {}
jobs:
  readme:
    name: Update Readme
    runs-on: windows-latest
    steps:
      - name: Check Third-party Repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $result = [System.Collections.Generic.List[object]]@()
          
          # TODO: Migration
          $repolist = @(
            @{repo_name = "abseil/abseil-cpp"; display_name="abseil"},
            @{repo_name = "weidai11/cryptopp"},
            @{repo_name = "microsoft/Detours"; display_name="detours"},
            @{repo_name = "gperftools/gperftools"},
            @{repo_name = "protocolbuffers/protobuf"},
            @{repo_name = "google/snappy"},
            @{repo_name = "NVIDIA/stdexec"}
          )
          
          $repolist | ForEach-Object {
            $repo = $_.repo_name
            if ((-not $_.ContainsKey("display_name")) -or ($_.display_name -eq "")) {
               $_.display_name = ($_.repo_name -split '/')[1]
            }
            $repo_info = gh repo view $repo --json latestRelease | ConvertFrom-Json
            $release = $repo_info.latestRelease
            $result.Add(@{
              repo_name = $_.repo_name;
              display_name = $_.display_name;
              tag_name = $release.tagName;
              publish_time = $release.publishedAt
            })
          }

          $result | Sort-Object -Property display_name | ForEach-Object {
            $_ | Format-Table -AutoSize
          }
