name: Update Readme
on:
  workflow_dispatch: {}
jobs:
  readme:
    name: Update Readme
    runs-on: windows-latest
    steps:
      - name: Check Third-party Repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $repo_list = @(
            @{repo_name = "protocolbuffers/protobuf"; display_name=""},
            @{repo_name = "weidai11/cryptopp"; display_name=""}
          )
          $repo_list | ForEach-Object {
            $repo = $_.repo_name
            $tags = git ls-remote --tags --sort=-v:refname https://github.com/$($repo).git
            # TODO: handle tags
            $release_info = gh release view --repo $repo --json tagName,publishedAt,isPrerelease
            $release_info | ConvertFrom-Json | ForEach-Object {
              $_ | Format-Table -AutoSize
            }
          }
