name: CI
on:
  workflow_dispatch: {}
jobs:
  readme:
    name: CI
    runs-on: windows-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v4
      
      - name: CMake Generate
        shell: pwsh
        run: |
          $cmake_dir = "${{ runner.temp }}\build"
          
          if ($cmake_dir.Contains(" ")) {
            Write-Warning "CMake working dir($cmake_dir) contains space"
          }
          
          if (-not (Test-Path -Path $cmake_dir)) {
            New-Item -Path $cmake_dir -ItemType "Directory"
          }
          
          Push-Location "$cmake_dir"
          
          Import-Module VSSetup
          
          $vs_instance = Get-VSSetupInstance | Select-VSSetupInstance -Latest
          $vs_dev_shell = Join-Path $.InstallationPath "Common7\Tools\Launch-VsDevShell.ps1"
          if (-not (Test-Path -Path $vs_dev_shell)) {
            Write-Error "vs_dev_shell $vs_dev_shell is invalid."
          }
          & $vs_dev_shell -Arch x64
          cl.exe
          Pop-Location
#         $vs = Get-VSSetupInstance | Where-Object {
#           $_.InstallationPath.Contains("Launch-VsDevShell.ps1")
#         }
#         $vs | Foreach-Object {
#           Write-Host "Found Launch-VsDevShell.ps1 for Visual Studio $($_.DisplayName) ($($_.InstallationVersion))"
#           Write-Host "Path: $_.InstallationPath"
#         }
#         
#         & ($vs[0]).InstallationPath -Arch x64
#         cl.exe
          
          
#      - name: CMake Build
#        shell: pwsh
#        run: |
#          
