name: Update Readme
on:
  workflow_dispatch: {}
jobs:
  readme:
    name: Update Readme
    runs-on: windows-latest
    steps:
      - name: Check Third-party Repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # TODO: Migration
          $repolist = @(
            @{repo_name = "abseil/abseil-cpp"; display_name="abseil"},
            @{repo_name = "weidai11/cryptopp"; display_name=""},
            @{repo_name = "microsoft/Detours"; display_name="detours"},
            @{repo_name = "gperftools/gperftools"; display_name=""},
            @{repo_name = "protocolbuffers/protobuf"; display_name=""},
            @{repo_name = "google/snappy"; display_name=""},
            @{repo_name = "NVIDIA/stdexec"; display_name=""}
          )
          $repolist | ForEach-Object {
            $repo = $_.repo_name
            
            $repo_info = gh repo view $repo --json latestRelease | ConvertFrom-Json
            $repo_info.latestRelease | ForEach-Object {
              $_ | Format-Table -AutoSize
            }

            # TODO: handle tags
            # $tags = git ls-remote --tags --sort=-v:refname https://github.com/$($repo).git

            #$release_info = gh release view --repo $repo --json tagName,publishedAt,isPrerelease
            
            #$release_info | ConvertFrom-Json | ForEach-Object {
            #  $_ | Format-Table -AutoSize
            #}
          }
