name: Update Readme
on:
  workflow_dispatch: {}
jobs:
  readme:
    name: Update Readme
    runs-on: windows-latest
    steps:
      - name: Check Third-party Repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # TODO: Migration
          $repolist = @(
            @{repo_name = "abseil/abseil-cpp"; display_name="abseil"},
            @{repo_name = "weidai11/cryptopp"; display_name=""},
            @{repo_name = "microsoft/Detours"; display_name="detours"},
            @{repo_name = "gperftools/gperftools"; display_name=""},
            @{repo_name = "protocolbuffers/protobuf"; display_name=""},
            @{repo_name = "google/snappy"; display_name=""},
            @{repo_name = "NVIDIA/stdexec"; display_name=""}
          )
          $repolist | ForEach-Object {
            $repo = $_.repo_name
            Write-Output $repo
            $repo_info = gh repo view $repo --json latestRelease | ConvertFrom-Json
            Write-Host $repo_info.latestRelease
          }
