name: Track CS2
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'
jobs:
  tracking:
    name: Track CS2
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set tracking dir
        id: set_tracking_dir
        shell: pwsh
        run: |
          "GameTracking_dir=${{ runner.temp }}\GameTracking-CS2" |
            Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

      - name: Clone latest repo
        id: clone
        shell: pwsh
        run: |
          $GameTracking_dir = "${{ steps.set_tracking_dir.outputs.GameTracking_dir }}"
          git clone --depth=1 https://github.com/SteamDatabase/GameTracking-CS2.git $GameTracking_dir
          
          # TODO: Waring if $GameTracking_dir.Contains(" ")
          
          $GameTracking_dir |
            Get-ChildItem -Force -Directory |
            Where-Object { -not $_.FullName.Contains(".git") } |
            ForEach-Object { XCOPY $_.FullName "GameTracking\CS2" /E /I /H /Y /Q }
          
          $changes = git status --porcelain
          if (-not $changes) {
              exit 0
          }

      - name: Commit changes
        id: commit
        shell: pwsh
        run: |
          Push-Location "${{ steps.set_tracking_dir.outputs.GameTracking_dir }}"
          $commit_sha = git rev-parse HEAD
          Pop-Location
          "COMMIT_SHA=$commit_sha" |
            Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "GameTracking-CS2: updated to ${{ steps.commit.outputs.COMMIT_SHA }}"
          base: master
          branch: update-tracking-cs2
          delete-branch: true
          author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: |
            GameTracking-CS2: updated to ${{ steps.commit.outputs.COMMIT_SHA }}
          body: |
            GameTracking-CS2: updated to ${{ steps.commit.outputs.COMMIT_SHA }}
