name: Track CS2
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'
jobs:
  tracking:
    name: Track CS2
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set tracking dir
        shell: pwsh
        run: |
          echo "GameTracking_dir=${{ runner.temp }}\GameTracking-CS2" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Clone latest repo
        shell: pwsh
        run: |
          git clone --depth=1 https://github.com/SteamDatabase/GameTracking-CS2.git "$env:GameTracking_dir"
          
          "$env:GameTracking_dir" | Get-ChildItem -Filter *.* | ForEach-Object { $_ | Remove-Item -Force }
          XCOPY "$env:GameTracking_dir" "GameTracking\CS2" /E /I /H /Y
          
          $changes = git status --porcelain
          if (-not $changes) {
              echo "TRACKING_CHANGED=false" | Out-File -FilePath $env:GITHUB_ENV -Append
              exit 0
          } else {
              echo "TRACKING_CHANGED=true" | Out-File -FilePath $env:GITHUB_ENV -Append
          }

      - name: Commit changes
        if: env.TRACKING_CHANGED == 'true'
        shell: pwsh
        run: |
          Push-Location "$env:GameTracking_dir"
          $commit_sha = git rev-parse HEAD
          Pop-Location
          echo "COMMIT_SHA=$commit_sha" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Create Pull Request
        if: env.TRACKING_CHANGED == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "GameTracking-CS2: updated to ${{ env.COMMIT_SHA }}"
          base: master
          branch: update-tracking-cs2
          delete-branch: true
          committer: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          commit-message: |
            GameTracking-CS2: updated to ${{ env.COMMIT_SHA }}
          body: |
            GameTracking-CS2: updated to ${{ env.COMMIT_SHA }}
