name: Update Readme
on:
  workflow_call:
    secrets:
      github-token:
        required: true
defaults:
  run:
    shell: pwsh
jobs:
  update_readme:
    name: Update readme
    runs-on: windows-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: '*_result_file'
          path: doc/auto_gen
          merge-multiple: true
          github-token: ${{ secrets.github-token }}
      
      - name: Generate readme.md
        id: generate_readme
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Import-Module MarkdownPS
          $markdown = ""
          $yaml_url = "https://github.com/$env:GITHUB_REPOSITORY/actions/workflows"
          
          #region headers
          
          $markdown += New-MDHeader "Readme"
          
          $url = "$yaml_url/ci.yaml"
          $svg = "[![CI]($url/badge.svg)]($url)`n"
          $markdown += $svg
          
          $url = "$yaml_url/track_cs2.yaml"
          $svg = "[![Track CS2]($url/badge.svg)]($url)`n"
          $markdown += $svg
          
          $url = "$yaml_url/update_readme.yaml"
          $svg = "[![Update Readme]($url/badge.svg)]($url)`n"
          $markdown += $svg
          
          $url = "cmake_detection.md&logo=cmake&label=CMake%20Detection)](#cmake-detection)"
          $svg = "[![](https://img.shields.io/github/last-commit/DuKeM-CSGO/CSGODemoTool-prop?path=doc%2Fauto_gen%2F$url`n"
          $markdown += $svg
          
          $url = "third_party_repo.md&logo=github&label=Third-party%20Repos)](#third-party-repos)"
          $svg = "[![](https://img.shields.io/github/last-commit/DuKeM-CSGO/CSGODemoTool-prop?path=doc%2Fauto_gen%2F$url`n"
          $markdown += $svg
          
          #region auto-gen
          Get-ChildItem "doc/auto_gen" -File |
            Select-Object FullName, LastWriteTimeUtc |
            Foreach-Object {
              $content = Get-Content -Path $_.FullName -Raw -Encoding utf8
              $markdown += $content
              $markdown += New-MDParagraph -Lines ""
            }
          
          $markdown | Out-File -FilePath readme.md -Force -Encoding utf8
          
          # check changes
          
          git add .
          $changes = git status --porcelain
          
          if (-not $changes) {
              Write-Host "Changes:\n$changes"
              exit 0
          } else {
              "readme_changed=true" |
                Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          }

      - name: Commit changes
        id: commit
        if: steps.generate_readme.outputs.readme_changed == 'true'
        run: |
          $commit_sha = git rev-parse HEAD
          "commit_sha=$commit_sha" |
            Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

      - name: Create Pull Request
        if: steps.generate_readme.outputs.readme_changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Readme: updated to ${{ steps.commit.outputs.commit_sha }}"
          base: master
          branch: update-readme-${{ steps.commit.outputs.commit_sha }}
          delete-branch: true
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: |
            Readme: updated to ${{ steps.commit.outputs.commit_sha }}
          body: |
            Readme: updated to ${{ steps.commit.outputs.commit_sha }}

#     - name: Check Github REST API
#       env:
#         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       run: |
#           $headers = @{
#             "Authorization" = "Bearer ${{ env.GH_TOKEN }}"
#             "Accept" = "application/vnd.github+json"
#           }
#           $response = Invoke-RestMethod -Uri "https://api.github.com/rate_limit" -Headers $headers -Method Get
#           $response |
#             ConvertTo-Json -Depth 5 |
#             Write-Host