name: Update Readme
on:
  workflow_call:
    secrets:
      github-token:
        required: true
defaults:
  run:
    shell: pwsh
jobs:
  update_readme:
    name: Update readme
    runs-on: windows-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: '*_result_file'
          path: doc/auto_gen
          merge-multiple: true
          github-token: ${{ secrets.github-token }}
      
      - name: Generate readme.md
        id: generate_readme
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          Import-Module MarkdownPS
          $markdown = ""
          $yaml_url = "https://github.com/$env:GITHUB_REPOSITORY/actions/workflows"
          
          #region headers
          
          $markdown += New-MDHeader "Readme"
          
          $url = "$yaml_url/ci.yaml"
          $svg = "[![CI]($url/badge.svg)]($url)"
          $markdown += New-MDParagraph -Lines $svg
          
          $url = "$yaml_url/track_cs2.yaml"
          $svg = "[![Track CS2]($url/badge.svg)]($url)"
          $markdown += New-MDParagraph -Lines $svg
          
          $url = "$yaml_url/update_readme.yaml"
          $svg = "[![Track CS2]($url/badge.svg)]($url)"
          $markdown += New-MDParagraph -Lines $svg
          
          #region auto-gen
          Get-ChildItem "doc/auto_gen" -File |
            Select-Object FullName, LastWriteTimeUtc |
            Foreach-Object {
              $content = Get-Content -Path $_.FullName -Raw -Encoding utf8
              $markdown += $content
              
              $footnote = "Last updated: " + $_.LastWriteTimeUtc.ToString("u")
              $markdown += New-MDCharacterStyle -Text "$footnote" -Style Italic
              $markdown += New-MDParagraph -Lines ""
            }
          
          $markdown | Out-File -FilePath readme.md -Force -Encoding utf8
          
          # check changes
          
          git add .
          $changes = git status --porcelain
          
          if (-not $changes) {
              Write-Host "Changes:\n$changes"
              exit 0
          } else {
              "readme_changed=true" |
                Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          }

      - name: Commit changes
        id: commit
        if: steps.generate_readme.outputs.readme_changed == 'true'
        shell: pwsh
        run: |
          $commit_sha = git rev-parse HEAD
          "commit_sha=$commit_sha" |
            Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

      - name: Create Pull Request
        if: steps.generate_readme.outputs.readme_changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Readme: updated to ${{ steps.commit.outputs.commit_sha }}"
          base: master
          branch: update-readme
          delete-branch: true
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: |
            Readme: updated to ${{ steps.commit.outputs.commit_sha }}
          body: |
            Readme: updated to ${{ steps.commit.outputs.commit_sha }}